import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Certificate Verified | GitProof",
  description: "This certificate has been verified by the GitProof platform.",
};

const GPLogo = ({ size = 40 }: { size?: number }) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width={size} height={size} fill="none">
    <path d="M16 2L29 7.5V15C29 22.5 23 28.5 16 30.5C9 28.5 3 22.5 3 15V7.5Z" fill="white" opacity="0.95"/>
    <path d="M10.5 16L14 19.5L21.5 12" stroke="#0d1117" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" fill="none"/>
  </svg>
);

export default async function VerifyPage({ params }: { params: { certId: string } }) {
  const certId = params.certId.toUpperCase();

  // Parse cert ID to extract info: GP-CERT-YYYY-MM-DD-XXXXXX
  const parts = certId.split("-");
  const isValid = parts[0] === "GP" && parts[1] === "CERT" && parts.length >= 6;
  const issuedDate = isValid ? `${parts[4]} ${parts[3]} ${parts[2]}` : "Unknown";

  return (
    <main style={{
      minHeight: "100vh",
      background: "linear-gradient(135deg,#0d1117 0%,#111827 50%,#0d1117 100%)",
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      justifyContent: "center",
      fontFamily: "Inter,-apple-system,system-ui,sans-serif",
      padding: "24px",
    }}>
      {/* Card */}
      <div style={{
        background: "white",
        borderRadius: 20,
        padding: "48px 52px",
        maxWidth: 520,
        width: "100%",
        boxShadow: "0 24px 80px rgba(0,0,0,0.5)",
        textAlign: "center",
      }}>
        {/* Logo */}
        <div style={{ display:"flex", flexDirection:"column", alignItems:"center", gap:8, marginBottom:28 }}>
          <div style={{ width:64, height:64, borderRadius:16, background:"linear-gradient(135deg,#111827,#0d1117)", display:"flex", alignItems:"center", justifyContent:"center", boxShadow:"0 4px 16px rgba(0,0,0,0.2)" }}>
            <GPLogo size={38}/>
          </div>
          <span style={{ fontWeight:800, fontSize:20, color:"#0d1117", letterSpacing:"-0.4px" }}>GitProof</span>
        </div>

        {/* Verified badge */}
        <div style={{
          width: 80, height: 80, borderRadius: "50%",
          background: "linear-gradient(135deg,#16a34a,#15803d)",
          display: "flex", alignItems: "center", justifyContent: "center",
          margin: "0 auto 20px",
          boxShadow: "0 0 0 8px rgba(22,163,74,0.12)",
        }}>
          <svg viewBox="0 0 24 24" width={40} height={40} fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M20 6L9 17l-5-5"/>
          </svg>
        </div>

        <h1 style={{ fontSize:26, fontWeight:900, color:"#0d1117", margin:"0 0 8px", letterSpacing:"-0.5px" }}>
          Certificate Verified
        </h1>
        <p style={{ fontSize:14, color:"#6b7280", margin:"0 0 28px", lineHeight:1.6 }}>
          This certificate is authentic and was generated by the GitProof platform.
        </p>

        {/* Cert info */}
        <div style={{ background:"#f9fafb", border:"1px solid #e5e7eb", borderRadius:12, padding:"16px 20px", textAlign:"left", marginBottom:24 }}>
          <div style={{ display:"flex", flexDirection:"column", gap:10 }}>
            <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center" }}>
              <span style={{ fontSize:11, color:"#9ca3af", textTransform:"uppercase", letterSpacing:"0.08em" }}>Certificate ID</span>
              <span style={{ fontSize:12, fontWeight:700, color:"#c9960c", fontFamily:"'Courier New',monospace" }}>{certId}</span>
            </div>
            <div style={{ height:1, background:"#e5e7eb" }}/>
            <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center" }}>
              <span style={{ fontSize:11, color:"#9ca3af", textTransform:"uppercase", letterSpacing:"0.08em" }}>Platform</span>
              <span style={{ fontSize:12, fontWeight:700, color:"#0d1117" }}>GitProof</span>
            </div>
            <div style={{ height:1, background:"#e5e7eb" }}/>
            <div style={{ display:"flex", justifyContent:"space-between", alignItems:"center" }}>
              <span style={{ fontSize:11, color:"#9ca3af", textTransform:"uppercase", letterSpacing:"0.08em" }}>Status</span>
              <span style={{ fontSize:12, fontWeight:700, color:"#16a34a", display:"flex", alignItems:"center", gap:4 }}>
                <svg viewBox="0 0 16 16" width={12} height={12} fill="currentColor"><path d="M8 16A8 8 0 108 0a8 8 0 000 16zm3.78-9.72a.75.75 0 00-1.06-1.06L6.75 9.19 5.28 7.72a.75.75 0 00-1.06 1.06l2 2a.75.75 0 001.06 0l4.5-4.5z"/></svg>
                Valid &amp; Authentic
              </span>
            </div>
          </div>
        </div>

        {/* Trust message */}
        <div style={{ display:"flex", alignItems:"center", gap:8, padding:"10px 14px", background:"#eff6ff", borderRadius:8, border:"1px solid #bfdbfe", marginBottom:24 }}>
          <svg viewBox="0 0 20 20" width={16} height={16} fill="#2563eb" style={{ flexShrink:0 }}>
            <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a.75.75 0 000 1.5h.253a.25.25 0 01.244.304l-.459 2.066A1.75 1.75 0 0010.747 15H11a.75.75 0 000-1.5h-.253a.25.25 0 01-.244-.304l.459-2.066A1.75 1.75 0 009.253 9H9z" clipRule="evenodd"/>
          </svg>
          <p style={{ fontSize:11.5, color:"#1d4ed8", margin:0, lineHeight:1.4 }}>
            This certificate was generated by GitProof, a platform for verifying and certifying GitHub repository milestones.
          </p>
        </div>

        <a href="/" style={{
          display:"inline-block", padding:"11px 28px",
          background:"linear-gradient(135deg,#111827,#0d1117)",
          color:"white", borderRadius:8, fontWeight:700, fontSize:13,
          textDecoration:"none", letterSpacing:"-0.2px",
        }}>
          ← Go to GitProof
        </a>
      </div>

      {/* Footer note */}
      <p style={{ color:"#4b5563", fontSize:11.5, marginTop:20, textAlign:"center" }}>
        © {new Date().getFullYear()} GitProof · Verifying developer achievements
      </p>
    </main>
  );
}
